// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Obligatorio_Programacion.Data;

#nullable disable

namespace Obligatorio_Programacion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadActual")
                        .HasColumnType("int");

                    b.Property<int>("CantidadMinima")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlerta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdMaterialObra")
                        .HasColumnType("int");

                    b.Property<int>("IdObra")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Resuelta")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdMaterialObra");

                    b.HasIndex("IdObra");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Asignacion", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdObra")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("IdObra");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DatosAnteriores")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DatosNuevos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionCambio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DireccionIP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdRegistro")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdAuditoria");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.AvanceTarea", b =>
                {
                    b.Property<int>("IdAvance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescripcionAvance")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaAvance")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdTarea")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeAvance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdAvance");

                    b.HasIndex("IdTarea");

                    b.ToTable("AvancesTareas");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DireccionCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ComprobanteCompra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoCompra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdObra")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("ObservacionCompra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCompra");

                    b.HasIndex("IdObra");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.DetalleCompra", b =>
                {
                    b.Property<int>("IdDetalleCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadComprada")
                        .HasColumnType("int");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int");

                    b.Property<double>("PrecioUnitario")
                        .HasColumnType("double");

                    b.HasKey("IdDetalleCompra");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdMaterial");

                    b.ToTable("DetallesCompras");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Gasto", b =>
                {
                    b.Property<int>("IdGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ComprobanteGasto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescGasto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaGasto")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdObra")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoGasto")
                        .HasColumnType("int");

                    b.Property<double>("MontoGasto")
                        .HasColumnType("double");

                    b.HasKey("IdGasto");

                    b.HasIndex("IdObra");

                    b.HasIndex("IdTipoGasto");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Material", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EstadoMaterial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreMaterial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("PrecioUnitario")
                        .HasColumnType("double");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdMaterial");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.MaterialObra", b =>
                {
                    b.Property<int>("IdMaterialObra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadMO")
                        .HasColumnType("int");

                    b.Property<string>("EstadoMO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int");

                    b.Property<int>("IdObra")
                        .HasColumnType("int");

                    b.HasKey("IdMaterialObra");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdObra");

                    b.ToTable("MaterialesObras");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Obra", b =>
                {
                    b.Property<int>("IdObra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DireccionObra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoObra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("NombreObra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Presupuesto")
                        .HasColumnType("double");

                    b.HasKey("IdObra");

                    b.HasIndex("IdCliente");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Oficio", b =>
                {
                    b.Property<int>("IdOficio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NombreOficio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("descripcionOficio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdOficio");

                    b.ToTable("Oficios");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DireccionProveedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailProveedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoProveedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RUT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoProveedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdProveedor");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.RolAdmin", b =>
                {
                    b.Property<int>("IdUsuarioAd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioAd");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("RolesAdmin");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.RolEmpleado", b =>
                {
                    b.Property<int>("IdUsuarioEmp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioEmp");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("RolesEmpleado");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Tarea", b =>
                {
                    b.Property<int>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescTarea")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoTarea")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdAsignacion")
                        .HasColumnType("int");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdTarea");

                    b.HasIndex("IdAsignacion");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.TelCliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCliente");

                    b.ToTable("TelClientes");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.TelProveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoProveedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdProveedor");

                    b.ToTable("TelProveedores");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.TelUsuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.ToTable("TelUsuarios");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.TipoGasto", b =>
                {
                    b.Property<int>("IdTipoGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NombreTipoGasto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdTipoGasto");

                    b.ToTable("TiposGasto");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdOficio")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoEmpleado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdOficio");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Alerta", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.MaterialObra", "MaterialObra")
                        .WithMany()
                        .HasForeignKey("IdMaterialObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obligatorio_Programacion.Entity.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialObra");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Asignacion", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obligatorio_Programacion.Entity.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.AvanceTarea", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("IdTarea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Compra", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obligatorio_Programacion.Entity.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.DetalleCompra", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.Compra", "Compra")
                        .WithMany()
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obligatorio_Programacion.Entity.Material", "Material")
                        .WithMany()
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Gasto", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obligatorio_Programacion.Entity.TipoGasto", "TipoGasto")
                        .WithMany()
                        .HasForeignKey("IdTipoGasto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("TipoGasto");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.MaterialObra", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.Material", "Material")
                        .WithMany()
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obligatorio_Programacion.Entity.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Obra", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.RolAdmin", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.RolEmpleado", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Tarea", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.Asignacion", "Asignacion")
                        .WithMany()
                        .HasForeignKey("IdAsignacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignacion");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.TelCliente", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.TelProveedor", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.TelUsuario", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Obligatorio_Programacion.Entity.Usuario", b =>
                {
                    b.HasOne("Obligatorio_Programacion.Entity.Oficio", "Oficio")
                        .WithMany()
                        .HasForeignKey("IdOficio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oficio");
                });
#pragma warning restore 612, 618
        }
    }
}
